# Generated by Django 4.0.2 on 2022-02-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_user_first_name_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
