# Generated by Django 4.0.2 on 2022-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
