# Generated by Django 4.0.2 on 2022-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_post_posted_content_post_posted_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_title',
            field=models.CharField(max_length=100),
        ),
    ]
