# Generated by Django 4.0.2 on 2022-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_username_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='cellphone',
            field=models.CharField(max_length=30),
        ),
    ]
