# Generated by Django 4.0.2 on 2022-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(default=0, max_length=50)),
                ('phone_number', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
