# Generated by Django 4.0.2 on 2022-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
