# Generated by Django 4.0.2 on 2022-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinformation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
