# Generated by Django 4.0.2 on 2022-02-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
