# Generated by Django 4.0.2 on 2022-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinformation_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
