# Generated by Django 4.0.2 on 2022-02-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_user',
            new_name='following',
        ),
    ]
