# Generated by Django 4.0.2 on 2022-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_followed_user_follow_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followeduser',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followuser',
        ),
    ]
